-- https://www.hackerrank.com/challenges/harry-potter-and-wands/

SELECT WANDS.ID, WANDS_PROPERTY.AGE, WANDS.COINS_NEEDED, WANDS.POWER
FROM WANDS
INNER JOIN WANDS_PROPERTY
ON WANDS.CODE = WANDS_PROPERTY.CODE
WHERE WANDS_PROPERTY.IS_EVIL = 0 AND 
    (WANDS_PROPERTY.AGE, WANDS.COINS_NEEDED, WANDS.POWER) IN 
        (SELECT WANDS_PROPERTY.AGE AS AGE, MIN(WANDS.COINS_NEEDED) AS MINCOINS, WANDS.POWER AS POWER
        FROM WANDS
        INNER JOIN WANDS_PROPERTY
        ON WANDS.CODE = WANDS_PROPERTY.CODE
        WHERE WANDS_PROPERTY.IS_EVIL = 0
        GROUP BY WANDS_PROPERTY.AGE, WANDS.POWER
        ) 
ORDER BY WANDS.POWER DESC, WANDS_PROPERTY.AGE DESC;