CREATE TABLE TEACHERS (
	TEACHER_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	HOMEROOM_NUMBER INTEGER,
	DEPARTMENT VARCHAR(100),
	EMAIL VARCHAR(100) UNIQUE,
	PHONE VARCHAR(100) UNIQUE
);

CREATE TABLE STUDENTS (
	STUDENT_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	HOMEROOM_NUMBER INTEGER ,
	PHONE VARCHAR(100) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	GRADUATION_YEAR INTEGER
);