INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, HOMEROOM_NUMBER, PHONE, GRADUATION_YEAR)
VALUES ('Mark', 'Watney', 5, '7775551234', 2035);

INSERT INTO TEACHERS (FIRST_NAME, LAST_NAME, HOMEROOM_NUMBER, DEPARTMENT, EMAIL, PHONE)
VALUES ('Jonas', 'Salk', 5, 'Biology', 'jsalk@school.org', '7775554321');