SELECT CD.FACILITIES.FACID, SUM(SLOTS)
FROM CD.FACILITIES
INNER JOIN CD.BOOKINGS
ON CD.FACILITIES.FACID = CD.BOOKINGS.FACID
WHERE EXTRACT(YEAR FROM STARTTIME) = 2012 AND EXTRACT(MONTH FROM STARTTIME) = 9
GROUP BY CD.FACILITIES.FACID
ORDER BY SUM(SLOTS);