-- https://www.hackerrank.com/challenges/weather-observation-station-20/

WITH ORDERED_TABLE AS (
SELECT
    LAT_N,
    ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROW_NUM
FROM
    STATION
)
SELECT ROUND(AVG(LAT_N),4) AS MEDIAN
FROM ORDERED_TABLE
WHERE ROW_NUM BETWEEN 
    (SELECT COUNT(*) FROM STATION)/2 
    AND 
    (SELECT COUNT(*) FROM STATION)/2 + 1
;