-- https://www.hackerrank.com/challenges/weather-observation-station-20/

WITH ORDERED_TABLE AS (
SELECT
    LAT_N,
    ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROW_NUM,
    (SELECT COUNT(*) FROM STATION) AS LEN_TABLE
FROM
    STATION
)
SELECT ROUND(AVG(LAT_N),4) AS MEDIAN
FROM ORDERED_TABLE
WHERE ROW_NUM BETWEEN LEN_TABLE/2 AND LEN_TABLE/2 + 1;